image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\bits
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64
    - x86

environment:
    BOOST_ROOT: "C:\\Libraries\\boost_1_67_0"
    BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_67_0\\lib64-msvc-14.0"
    PATH: "%BOOST_LIBRARYDIR%;%PATH%"

configuration:
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc10
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc14

build_script:
    - echo "%PATH%"
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DYEAR=11
    - cmake --build .
    - start bit_algo.exe
