image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\bits
shallow_clone: true

matrix:
    fast_finish: true

platform:
    - x64
    - x86

configuration:
    - Release

environment:
    CONFIG: Release
    BOOST_ROOT: "C:\\Libraries\\boost_1_67_0"
    BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_67_0\\lib64-msvc-14.0"
    PATH: "%BOOST_LIBRARYDIR%;%PATH%"

    matrix:
        - TOOLCHAIN: msvc10
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc14

build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="%CONFIG%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DYEAR=11
    - cmake -DCMAKE_BUILD_TYPE="%CONFIG%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DYEAR=11 --build .
    - ctest -C Release -V
