image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\bits
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc10
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc15

build_script:
    - mkdir build
    - cd build
    - cmake .. -DBOOST_ROOT=C:\Libraries\boost_1_67_0 -DYEAR=11
    - cmake --build .
    - start bit_algo.exe
