dist: trusty
sudo: false
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - sudo wget -O boost_1_68_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.68.0/boost_1_68_0.tar.gz/download >/dev/null 2>&1
    - sudo tar xzvf boost_1_68_0.tar.gz >/dev/null 2>&1
    - cd boost_1_68_0/
    - sudo ./bootstrap.sh --prefix=/usr/local -with-libraries=random,system,chrono >/dev/null 2>&1
    - sudo ./b2 link=shared threading=multi variant=release >/dev/null 2>&1
    - sudo ./b2 install >/dev/null 2>&1

branches:
  only:
    - master

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - make
